nlp/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
]

nlp/named_entity_recognition/urls.py
from django.urls import path

from named_entity_recognition.views import NERView

app_name = 'named_entity_recognition'

urlpatterns = [
    path('', NERView.as_view(), name='index'),
]

nlp/nlp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('named_entity_recognition', include('named_entity_recognition.urls',
                                             namespace="named_entity_recognition")),

    path('', include('core.urls',
                     namespace="core")),
]

nlp/core/models.py
from django.db import models

# Create your models here.

nlp/core/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, "core/main.html")

nlp/named_entity_recognition/views.py
from django.shortcuts import render
from django.views import View

from starter_codes.NER.MEM import MEMM

class NERView(View):
    def get(self, request):
        return render(request, "named_entity_recognition/form.html")

    def post(self, request):
        textarea = request.POST['textarea']
        classifier = MEMM()

        words, result = classifier.predict_sentence(textarea)
        tags = result.copy()

        for i, word in enumerate(words):
            if result[i] == "PERSON":
                words[i] = f"<mark class='text-danger'>{word}</mark>"

        classification_result = f"<p class='col-md-8 fs-4'>{' '.join(words)}</p>"

        return render(request, "named_entity_recognition/ner_result.html",
                      {"classification_result": classification_result,
                       "textarea_input": textarea,
                       "tags": tags})

nlp/core/templates/core/base.html
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
    <title>{% block title %}Change title{% endblock %}</title>
</head>
<body>
{% block header %}
{% endblock %}
<div class="container">
    {% block body %}
        <h1>Change body</h1>
    {% endblock %}
</div>
</body>
</html>

nlp/core/templates/core/form.html
{% extends "core/base.html" %}
{% block body %}
    {% include "core/header.html" %}
    <div class="container">
        {% block description %}{% endblock %}
        {% block result %}{% endblock %}
        <form action="{% block form_action_url %}{% endblock %}" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label for="" class="form-label">Input text here</label>
                <textarea name="textarea" placeholder="Input text here" id="" cols="30" rows="10"
                          class="form-control"
                          style="resize: none;">{{ textarea_input }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

nlp/core/templates/core/header.html
<div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
        <a href="{% url "core:index" %}" class="d-flex align-items-center text-dark text-decoration-none">
            <i style="width:40px;" class="bi bi-arrow-left"></i>
            <span class="fs-4">Main</span>
        </a>
    </header>
</div>

nlp/core/templates/core/main.html
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">CISC3025 - Natural language processing</h1>
            <h1 class="display-4">Course project</h1>
            <p class="col-md-8 fs-4">This webapp is developed to fulfill the requirements of CISC3025 - Natural language processing. </p>
            <a href="{% url 'named_entity_recognition:index' %}" class="btn btn-primary btn-lg mb-4 mr-2" type="button">Named entity recognition</a>
        </div>
    </div>
</div>
</body>
</html>

nlp/named_entity_recognition/templates/named_entity_recognition/form.html
{% extends "core/form.html" %}
{% block title %}Named Entity Recognition {% endblock %}
{% block description %}
    <div class="mb-4">
        <div class="container-fluid">
            <h1 class="display-5 fw-bold mb-5">Named entity recognition</h1>
            <p class="col-md-8 fs-4">
                Maximum entropy named entity recognition model
            </p>
        </div>
    </div>
{% endblock %}
{% block form_action_url %}{% url "named_entity_recognition:index" %}{% endblock %}

nlp/named_entity_recognition/templates/named_entity_recognition/ner_result.html
{% extends "core/form.html" %}
{% block title %}Named entity recognition - result{% endblock %}
{% block result %}
    <div class="mb-4 rounded-3">
        <div class="container-fluid">
            <h1 class="display-5 fw-bold mb-3">Classification results</h1>
            {{ classification_result|safe }}
            <p>Tags: {{ tags }}</p>
        </div>
    </div>
{% endblock %}
{% block form_action_url %}{% url "named_entity_recognition:index" %}{% endblock %}